# Generated by Django 2.1.2 on 2018-10-24 03:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the product category (e.g. Pre-Workout)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='7 Character Code. Must be first 4 characters of the brand followed by yy-mm-dd', max_length=10, verbose_name='Product Code')),
                ('description', models.TextField(help_text='Enter a brief description of the product', max_length=200)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_percent', models.IntegerField()),
                ('service_size', models.IntegerField(help_text='Enter product serving size.')),
                ('flavor', models.CharField(help_text='Enter available flavors for product.', max_length=20, verbose_name='Flavors')),
                ('inventory_amount', models.IntegerField(help_text='Enter inventory amount for product.')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Brand')),
                ('category', models.ManyToManyField(help_text='Select a category for this product', to='inventory.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this product.', primary_key=True, serialize=False)),
                ('flavor', models.CharField(help_text='Enter available flavors for product, one per line.', max_length=200, verbose_name='Flavors')),
                ('status', models.CharField(blank=True, choices=[('y', 'In Stock'), ('n', 'Out of Stock')], default='n', help_text='Product Availability', max_length=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Product')),
            ],
        ),
    ]
