# Generated by Django 2.1.2 on 2018-10-24 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flavor',
        ),
    ]
