# Generated by Django 2.1.2 on 2018-10-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_flavor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='service_size',
            new_name='serving_size',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='Must be first 4 characters of the brand followed by yy-mm-dd', max_length=10, verbose_name='Product Code'),
        ),
    ]
