# Generated by Django 2.1.2 on 2018-10-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20181023_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(help_text='Enter available flavors', max_length=200, verbose_name='Flavors')),
            ],
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='flavor',
        ),
        migrations.AddField(
            model_name='product',
            name='flavors',
            field=models.ManyToManyField(help_text='Select available flavors for this product', to='inventory.Flavors'),
        ),
    ]
