# Generated by Django 2.1.2 on 2018-10-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20181023_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(help_text='Enter available flavors', max_length=200, verbose_name='Flavor')),
            ],
        ),
        migrations.DeleteModel(
            name='Flavors',
        ),
        migrations.AlterField(
            model_name='product',
            name='flavors',
            field=models.ManyToManyField(help_text='Select available flavors for this product', to='inventory.Flavor'),
        ),
    ]
