# Generated by Django 2.1.2 on 2018-10-24 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20181023_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={'permissions': (('can_mark_stock', 'Set product as in stock'),)},
        ),
    ]
