# Generated by Django 2.1.2 on 2018-11-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20181024_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
