# Generated by Django 2.1.2 on 2018-12-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20181212_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(help_text='Select available categories', to='inventory.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(help_text='Must be first 3 characters of the brand followed by yy-hh-mm', max_length=10, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flavors',
            field=models.ManyToManyField(help_text='Select available flavors', to='inventory.Flavor'),
        ),
    ]
